### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Logiase** [hjmmc/WebGyroForCemuhook#5]
Error: listen EACCES (net.js 837:11)
    at errnoException (net.js:837:11)
    at Server.prototype._listen2 (net.js:951:19)
    at listen (net.js:997:5)
    at Server.prototype.listen/< (net.js:1078:9)
    at asyncCallback/< (dns.js:49:9)
    at _tickCallback (node.js:9

Windows10 1903

**Comment by hjmmc** [comment]
某个的端口被你的系统其他程序占用了

程序默认监听以下端口，请自行下载源码修改相应端口后安装 [nodejs](http://nodejs.cn/download/) 环境运行。

- UDP：26760（重力感应数据传输端口）
- TCP：8080、8443 （Web页面）
